#!/usr/bin/env python3
"""Phase 57 (D-04/D-06) -- pinned-extract generator for the `operationType`
enum carried by the vendored Revenium OpenAPI spec.

Implements D-04 (the allowed-values list enters the repo as a pinned
extract with spec provenance, generated by a committed extractor, never
hand-typed) and D-06 (the OAS stays gitignored in `.planning/research/`;
this extractor takes the OAS path as an argument and is operator-run only).

Committed, stdlib-only, operator-invoked tool. NOT a `test_*.py` module --
the filename deliberately does not match the discovery pattern, so it
never runs as part of `python3 -m unittest discover -s tests -p 'test_*.py'`.
Run it directly:

    python3 tests/extract_operation_type_enum.py \
        .planning/research/revenium-oas-v2.20.0-SNAPSHOT.json

Modelled on tests/mutation_verify_aux_atomicity.py's own header/posture
idiom: committed, stdlib-only, operator-invoked, deliberately not
discoverable by unittest.

Walks components.schemas.*.properties.operationType looking for an `enum`
key. This session's own scouting found 12 schemas carrying an identical
17-value operationType enum in the 2.20.0-SNAPSHOT OAS; this extractor
asserts that cross-schema equality itself (as an ordered-tuple comparison)
rather than trusting a single primary schema, so a future OAS bump that
silently diverges one schema from the rest fails loudly at regeneration
time instead of producing a stale or partial extract.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_OUT = Path(__file__).resolve().parent / 'fixtures' / 'spec' / 'operation-type-enum.json'
PRIMARY_SCHEMA = 'AICompletionMetricResource'
PRIMARY_POINTER = (
    f'#/components/schemas/{PRIMARY_SCHEMA}/properties/operationType/enum'
)


def _usage() -> str:
    return (
        'usage: python3 tests/extract_operation_type_enum.py <oas-path> [--out <output-path>]\n'
        '\n'
        'Generates tests/fixtures/spec/operation-type-enum.json (or --out) from the\n'
        'operationType enum(s) found in the given vendored OpenAPI spec.'
    )


def _parse_args(argv):
    if not argv:
        raise SystemExit(_usage())
    oas_arg = None
    out_arg = None
    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg == '--out':
            i += 1
            if i >= len(argv):
                raise SystemExit(_usage())
            out_arg = argv[i]
        elif oas_arg is None:
            oas_arg = arg
        else:
            raise SystemExit(_usage())
        i += 1
    if oas_arg is None:
        raise SystemExit(_usage())
    return oas_arg, out_arg


def load_spec(oas_path_arg: str) -> dict:
    oas_path = Path(oas_path_arg).resolve()
    if not oas_path.exists():
        raise SystemExit(f'ERROR: OAS file not found: {oas_path}')
    try:
        with open(oas_path, 'r', encoding='utf-8') as f:
            spec = json.load(f)
    except json.JSONDecodeError as exc:
        raise SystemExit(f'ERROR: {oas_path} is not valid JSON: {exc}')
    if not isinstance(spec, dict):
        raise SystemExit(f'ERROR: {oas_path} does not decode to a JSON object')
    return spec


def collect_operation_type_enums(spec: dict) -> dict:
    """Return {schema_name: [enum values...]} for every schema whose
    properties.operationType carries an `enum` key."""
    schemas = spec.get('components', {}).get('schemas', {})
    hits = {}
    for name, schema in schemas.items():
        if not isinstance(schema, dict):
            continue
        props = schema.get('properties', {})
        if not isinstance(props, dict):
            continue
        op_type = props.get('operationType')
        if isinstance(op_type, dict) and 'enum' in op_type:
            hits[name] = list(op_type['enum'])
    return hits


def build_extract(spec: dict, oas_path_arg: str) -> dict:
    hits = collect_operation_type_enums(spec)
    if len(hits) < 2:
        raise SystemExit(
            f'ERROR: expected at least 2 schemas carrying an operationType enum, '
            f'found {len(hits)}. Refusing to write a possibly-stale extract.'
        )
    if PRIMARY_SCHEMA not in hits:
        raise SystemExit(
            f'ERROR: primary schema {PRIMARY_SCHEMA!r} not found among the '
            f'operationType-carrying schemas: {sorted(hits)}'
        )

    # Cross-schema equality, as ordered tuples -- a divergence here is a
    # loud failure at regeneration time, not a silent single-schema read.
    distinct = {tuple(v) for v in hits.values()}
    if len(distinct) != 1:
        raise SystemExit(
            'ERROR: operationType enum diverged across schemas -- spec is no '
            f'longer uniform. Schemas and their values: {hits!r}'
        )

    values = list(hits[PRIMARY_SCHEMA])
    corroborating_pointers = sorted(
        f'#/components/schemas/{name}/properties/operationType/enum'
        for name in hits
        if name != PRIMARY_SCHEMA
    )

    return {
        'enum': 'operationType',
        'values': values,
        'source_spec_file': Path(oas_path_arg).name,
        'source_spec_version': spec.get('info', {}).get('version', ''),
        'openapi': spec.get('openapi', ''),
        'primary_pointer': PRIMARY_POINTER,
        'corroborating_pointers': corroborating_pointers,
        'extracted_by': 'tests/extract_operation_type_enum.py',
        'extracted_at': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
    }


def main(argv) -> int:
    oas_arg, out_arg = _parse_args(argv)
    spec = load_spec(oas_arg)
    extract = build_extract(spec, oas_arg)

    out_path = Path(out_arg).resolve() if out_arg else DEFAULT_OUT
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(extract, f, indent=2, sort_keys=False)
        f.write('\n')

    print(f'Wrote {len(extract["values"])} operationType values to {out_path}')
    print(f'  primary_pointer: {extract["primary_pointer"]}')
    print(f'  corroborating_pointers: {len(extract["corroborating_pointers"])}')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
