"""Phase 57 Plan 01 (D-04/D-05/D-06): the repo's FIRST test cross-checking
two independently-sourced EXTERNAL witnesses.

This is the direct answer to the failure mode named in the roadmap: "four
test modules, a golden argv fixture, and a CLI double all agreed with each
other, and none of them could validate a server-side enum." Every existing
aux test in this repo (test_phase55_auxiliary_metering.py,
test_compat_meter_completion_aux.py, test_phase56_aux_atomicity.py,
test_phase56_dry_run.py) asserts the emitted `--operation-type` value
against a Python literal the repo itself authored. That proves argv shape,
flag ordering, atomicity, and mirror-leak avoidance -- it proves nothing
about whether Revenium's server would actually ACCEPT the value, because a
fixture that agrees with itself cannot catch a server-side contract it has
never seen.

The risk this module is designed against: passing while only ever
consulting ONE witness dressed up as two. It is trivial to write a test
that *looks* like a two-witness check but actually just asserts the same
literal twice under different names. Every assertion below is built to make
that specific failure mode structurally impossible:

  - Witness A (the pinned, GENERATED extract at
    tests/fixtures/spec/operation-type-enum.json, produced by
    tests/extract_operation_type_enum.py from the vendored 2.20.0-SNAPSHOT
    OAS) is loaded by `_load_witness_a()`, a `json.load` over a file path.
  - Witness B (the verbatim server rejection transcript already committed
    at docs/comprehensive-roi-proof.md:191) is loaded by
    `_load_witness_b()`, a `re.search` over that document's live text at
    test-run time.
  - The two loaders share no parser, no constant, and no helper. Neither
    witness's value list appears as a Python literal ANYWHERE in this
    module -- if you are tempted to add one while debugging a failure here,
    that is the exact defect this module exists to prevent.
  - The emitted value under test is captured by driving the REAL
    `skills/revenium/scripts/hermes-report.sh` end to end (via
    tests/_compat_helpers.py, the same harness Phase 55/56 use), and is
    selected by its `--task-type` value matching `^aux_` -- NEVER by its
    `--operation-type` value, which would make the membership assertion
    circular (selecting the very thing you are about to assert membership
    of).
"""
from __future__ import annotations

import json
import os
import re
import shlex
import shutil
import tempfile
import unittest
from pathlib import Path

from tests._compat_helpers import (
    argv_to_flags,
    build_session_model_usage,
    build_shim,
    build_state_db,
    run_script,
    SCRIPTS_DIR,
)

ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / 'skills' / 'revenium'
EXTRACT_PATH = ROOT / 'tests' / 'fixtures' / 'spec' / 'operation-type-enum.json'
ROI_PROOF_DOC = ROOT / 'docs' / 'comprehensive-roi-proof.md'
COMMON_SH = SKILL / 'scripts' / 'common.sh'


def _load_witness_a(extract_path=EXTRACT_PATH):
    """Witness A: json.load the generated extract file. Raises loudly on
    any absent/empty/malformed input -- see WitnessLoaderFailsLoudTests."""
    path = Path(extract_path)
    if not path.exists():
        raise FileNotFoundError(
            f'D-04/D-05 witness A missing: {path} does not exist. The extract '
            'must be generated by tests/extract_operation_type_enum.py before '
            'this test can run -- it is never allowed to silently pass without it.'
        )
    text = path.read_text(encoding='utf-8')
    if not text.strip():
        raise ValueError(
            f'D-04/D-05 witness A empty: {path} has no content. A blank extract '
            'is a loud failure, never a vacuous pass.'
        )
    data = json.loads(text)
    values = data.get('values')
    if not values:
        raise ValueError(
            f'D-04/D-05 witness A carries an empty or missing "values" list in '
            f'{path}. An empty allowed-values list is a loud failure, never a '
            'vacuous pass.'
        )
    return data


def _load_witness_b(doc_path=ROI_PROOF_DOC):
    """Witness B: regex-extract the verbatim server allowed-values line out
    of docs/comprehensive-roi-proof.md's LIVE text at test-run time. Raises
    loudly if the anchor line is gone -- see WitnessLoaderFailsLoudTests."""
    path = Path(doc_path)
    if not path.exists():
        raise FileNotFoundError(
            f'D-05 witness B missing: {path} does not exist.'
        )
    doc_text = path.read_text(encoding='utf-8')
    match = re.search(r'Allowed values: \[([^\]]+)\]', doc_text)
    if not match:
        raise ValueError(
            f'D-05 witness B: {path} no longer carries the "Allowed values: '
            '[...]" line this test depends on. This is a loud failure, never '
            'a skip.'
        )
    return [v.strip() for v in match.group(1).split(',')]


def _common_sh_aux_operation_type_default():
    """Parse the AUX_OPERATION_TYPE declaration's default straight out of
    common.sh's own text -- an independent read of the shipped constant,
    not a restatement of what this test module assumes it to be."""
    text = COMMON_SH.read_text(encoding='utf-8')
    match = re.search(
        r'AUX_OPERATION_TYPE="\$\{REVENIUM_AUX_OPERATION_TYPE:-([^}]+)\}"',
        text,
    )
    if not match:
        raise ValueError(
            'AUX_OPERATION_TYPE declaration not found in common.sh in the '
            'expected D-02 form.'
        )
    return match.group(1)


def _drive_real_reporter_for_one_aux_row():
    """Drive the REAL hermes-report.sh over a synthetic state.db carrying
    one sessions row and one non-empty-task session_model_usage row.
    Returns the list of captured meter-completion invocations (argv lists).
    """
    sid = 'spec-membership-sid-001'
    session = {
        'id': sid, 'model': 'claude-sonnet-4-6', 'source': 'test',
        'input_tokens': 100, 'output_tokens': 50, 'cache_read': 0, 'cache_write': 0,
        'reasoning': 0, 'estimated_cost': '0', 'api_calls': 1,
        'started_at': 1715514000.0, 'ended_at': 1715514000.0, 'billing_provider': 'anthropic',
    }
    aux_row = {
        'session_id': sid, 'model': 'claude-3-5-haiku', 'billing_provider': 'anthropic',
        'billing_base_url': '', 'billing_mode': '', 'task': 'approval',
        'api_call_count': 3, 'input_tokens': 40, 'output_tokens': 10,
        'cache_read_tokens': 0, 'cache_write_tokens': 0, 'estimated_cost_usd': 0.002,
        'first_seen': 1715514500.0, 'last_seen': 1715514600.0,
    }

    tmpdir = tempfile.mkdtemp(prefix='gsd-phase57-opspec-')
    try:
        hermes_home = os.path.join(tmpdir, 'hh')
        state_dir = os.path.join(hermes_home, 'state', 'revenium')
        markers_dir = os.path.join(state_dir, 'markers')
        os.makedirs(markers_dir, mode=0o700)
        state_db = os.path.join(hermes_home, 'state.db')

        shim_home = os.path.join(tmpdir, 'home')
        bin_dir = os.path.join(shim_home, '.local', 'bin')
        os.makedirs(bin_dir)
        shim = os.path.join(bin_dir, 'revenium')

        build_state_db(state_db, [session])
        build_session_model_usage(state_db, [aux_row])
        build_shim(shim)

        meter_log = os.path.join(tmpdir, 'meter.log')
        jobs_log = os.path.join(tmpdir, 'jobs.log')
        inv_log = os.path.join(tmpdir, 'inv.log')
        env = {
            **os.environ,
            'HOME': shim_home,
            'HERMES_HOME': hermes_home,
            'REVENIUM_STATE_DIR': state_dir,
            'PATH': bin_dir + os.pathsep + os.environ.get('PATH', ''),
            'INVOCATIONS_LOG': inv_log,
            'METER_LOG': meter_log,
            'JOBS_LOG': jobs_log,
            'TZ': 'UTC',
        }
        rc, _ignored_inv, output = run_script(
            SCRIPTS_DIR / 'hermes-report.sh', env, inv_log
        )
        if rc != 0:
            raise AssertionError(f'hermes-report.sh failed (rc={rc}): {output}')

        meter_invocations = []
        if os.path.exists(meter_log):
            with open(meter_log) as f:
                for line in f:
                    line = line.rstrip('\n')
                    if line:
                        meter_invocations.append(shlex.split(line))
        return meter_invocations
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


class SpecExtractProvenanceTests(unittest.TestCase):
    """The generated extract must carry a full provenance envelope so drift
    is detectable by re-running the extractor and diffing (T-57-01)."""

    def test_extract_carries_spec_provenance(self):
        data = _load_witness_a()
        for key in (
            'enum', 'values', 'source_spec_file', 'source_spec_version',
            'openapi', 'primary_pointer', 'corroborating_pointers',
            'extracted_by', 'extracted_at',
        ):
            self.assertIn(
                key, data,
                f'D-04 provenance envelope missing key {key!r} in the generated extract',
            )
            self.assertTrue(
                data[key] or data[key] == [],
                f'D-04 provenance key {key!r} must be non-empty (except an '
                'intentionally-empty list, which corroborating_pointers is not)',
            )
        self.assertTrue(
            data['source_spec_version'].startswith('2.20.0'),
            f'D-04 extract must be sourced from the 2.20.0 OAS, got '
            f'source_spec_version={data["source_spec_version"]!r}',
        )

    def test_extract_records_all_corroborating_pointers(self):
        data = _load_witness_a()
        self.assertEqual(
            1 + len(data['corroborating_pointers']), 12,
            'D-04: the extractor must record the primary pointer plus all 11 '
            'corroborating schema pointers -- 12 total operationType-carrying '
            'schemas in the 2.20.0-SNAPSHOT OAS',
        )
        self.assertEqual(
            data['extracted_by'], 'tests/extract_operation_type_enum.py',
            'D-06: extracted_by must name the operator-run extractor script path',
        )


class TwoWitnessAgreementTests(unittest.TestCase):
    """D-05: the extract (witness A) must agree with the verbatim server
    rejection transcript already committed at docs/comprehensive-roi-proof.md
    (witness B) -- as an ORDERED sequence, not mere set membership. A
    reordering of either witness is a real signal and must fail this test."""

    def test_witness_a_and_witness_b_are_identical_ordered_sequences(self):
        witness_a = _load_witness_a()['values']
        witness_b = _load_witness_b()

        self.assertEqual(
            len(witness_a), 17,
            f'D-05 witness A must carry exactly 17 operationType values, got '
            f'{len(witness_a)}: {witness_a!r}',
        )
        self.assertEqual(
            len(witness_b), 17,
            f'D-05 witness B must carry exactly 17 operationType values, got '
            f'{len(witness_b)}: {witness_b!r}',
        )
        self.assertEqual(
            witness_a, witness_b,
            'D-05: the OAS-sourced extract (witness A) and the verbatim server '
            'rejection transcript (witness B) must be identical ORDERED '
            'sequences. A divergence here — in membership OR order — is a '
            'real signal, not noise: it means the spec and the live server '
            'have drifted apart, or one of the two committed artifacts is stale.',
        )


class EmittedValueMembershipTests(unittest.TestCase):
    """The core proof: drive the REAL reporter, capture what it ACTUALLY
    puts on the wire, and check that against the spec-sourced list -- not
    against another fixture that only agrees with itself."""

    def test_reporter_emitted_operation_type_is_a_member_of_the_spec_enum(self):
        invocations = _drive_real_reporter_for_one_aux_row()
        flagged = [argv_to_flags(inv) for inv in invocations]

        # Select the auxiliary invocation by --task-type matching ^aux_,
        # NEVER by --operation-type -- selecting by the very field under
        # test would make this assertion circular (SSE-01 adjacency edge).
        aux_invocations = [
            f for f in flagged
            if re.match(r'^aux_', str(f.get('--task-type', '')))
        ]
        self.assertEqual(
            len(aux_invocations), 1,
            f'expected exactly 1 invocation with --task-type matching ^aux_, '
            f'got {len(aux_invocations)}: {flagged!r}',
        )
        aux_flags = aux_invocations[0]

        witness_a = _load_witness_a()['values']
        emitted = aux_flags.get('--operation-type')
        self.assertIn(
            emitted, witness_a,
            f'the REAL reporter emitted --operation-type {emitted!r}, which is '
            f'NOT a member of the spec-sourced allowed-values list {witness_a!r}. '
            'This is the exact defect this phase exists to fix.',
        )

    def test_the_emitted_value_is_the_common_sh_constant(self):
        invocations = _drive_real_reporter_for_one_aux_row()
        flagged = [argv_to_flags(inv) for inv in invocations]
        aux_invocations = [
            f for f in flagged
            if re.match(r'^aux_', str(f.get('--task-type', '')))
        ]
        self.assertEqual(len(aux_invocations), 1)
        emitted = aux_invocations[0].get('--operation-type')

        default_value = _common_sh_aux_operation_type_default()
        self.assertEqual(
            emitted, default_value,
            'D-02: the emitted value must equal the AUX_OPERATION_TYPE default '
            "declared in common.sh -- the reporter must resolve its value from "
            'that single named constant, not a call-site literal.',
        )


class WitnessLoaderFailsLoudTests(unittest.TestCase):
    """The companion invariant to the assumption-delta promote decision:
    a witness that cannot be read is a FAILURE, never a skip and never a
    vacuous pass. Each case here asserts the loader raises."""

    def test_missing_extract_path_raises(self):
        with self.assertRaises(FileNotFoundError):
            _load_witness_a(extract_path=ROOT / 'tests' / 'fixtures' / 'spec' / 'does-not-exist.json')

    def test_empty_json_object_extract_raises(self):
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
            f.write('{}')
            path = f.name
        try:
            with self.assertRaises(ValueError):
                _load_witness_a(extract_path=Path(path))
        finally:
            os.unlink(path)

    def test_empty_values_list_extract_raises(self):
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
            json.dump({'enum': 'operationType', 'values': []}, f)
            path = f.name
        try:
            with self.assertRaises(ValueError):
                _load_witness_a(extract_path=Path(path))
        finally:
            os.unlink(path)

    def test_doc_missing_allowed_values_line_raises(self):
        with tempfile.NamedTemporaryFile(mode='w', suffix='.md', delete=False) as f:
            f.write('# some doc with no allowed-values line in it at all\n')
            path = f.name
        try:
            with self.assertRaises(ValueError):
                _load_witness_b(doc_path=Path(path))
        finally:
            os.unlink(path)


class SoleOtherEmitterTests(unittest.TestCase):
    """SSE-01 adjacency edge guard: the auxiliary pass must be the ONLY
    emission site in skills/revenium/scripts/ that can send the new
    operationType value. Every OTHER --operation-type call site is
    enumerated here explicitly so a future addition is forced through this
    test rather than silently widening the population that could send the
    value under test."""

    # The complete, confirmed set of --operation-type emission sites in
    # skills/revenium/scripts/ as of this phase, and what each is allowed
    # to send. A future 5th site must be added here deliberately.
    _ALLOWED_VALUE_EXPRESSIONS = {
        '${AUX_OPERATION_TYPE}',
        '${op_type}',
        '${operation_type_r}',
        'CHAT',
    }

    def test_no_other_emission_site_sends_the_aux_operation_type(self):
        scripts_dir = SKILL / 'scripts'
        pattern = re.compile(r'--operation-type\s+"([^"]+)"')
        found = []
        for sh_file in sorted(scripts_dir.glob('*.sh')):
            text = sh_file.read_text(encoding='utf-8')
            for lineno, line in enumerate(text.splitlines(), start=1):
                stripped = line.strip()
                if stripped.startswith('#'):
                    continue
                match = pattern.search(line)
                if match:
                    found.append((sh_file.name, lineno, match.group(1)))

        self.assertEqual(
            len(found), 4,
            f'expected exactly 4 --operation-type emission sites in '
            f'skills/revenium/scripts/*.sh, found {len(found)}: {found!r}. '
            'A new site must be reviewed and added to this test deliberately.',
        )

        for filename, lineno, value in found:
            self.assertIn(
                value, self._ALLOWED_VALUE_EXPRESSIONS,
                f'{filename}:{lineno} sends --operation-type {value!r}, which is '
                f'not one of the confirmed-safe expressions {self._ALLOWED_VALUE_EXPRESSIONS!r}',
            )

        # The exact enumerated set this phase confirmed, so a change in
        # WHICH lines carry the flag (not just how many) is also caught.
        found_locations = {(f, l) for f, l, _v in found}
        expected_locations = {
            ('hermes-report.sh', 1248),
            ('hermes-report.sh', 3256),
            ('hermes-report.sh', 3422),
            ('api-event-report.sh', 1457),
        }
        self.assertEqual(
            found_locations, expected_locations,
            f'the set of --operation-type emission sites moved: found '
            f'{found_locations!r}, expected {expected_locations!r}',
        )


if __name__ == '__main__':
    unittest.main()
